!
	SUBROUTINE ROTATE_Y_d(ANGLE,X_INIT,X_TRANS)
			implicit none
!
			REAL*8 angle,X_INIT(3),X_TRANS(3)
!
	X_TRANS(1)=X_INIT(1)*COS(ANGLE)+X_INIT(3)*SIN(ANGLE)
	X_TRANS(2)=X_INIT(2)
	X_TRANS(3)=X_INIT(3)*COS(ANGLE)-X_INIT(1)*SIN(ANGLE)
!
	RETURN
	END
